Benchmark:
  name: "Face Recognition Benchmark"
  type: "Recognition"
  data:
    path: "benchmark/data/face_recognition"
    files: ["Aaron_Tippin_0001.jpg", "Alvaro_Uribe_0028.jpg", "Alvaro_Uribe_0029.jpg", "Jose_Luis_Rodriguez_Zapatero_0001.jpg"]
  metric: # 'sizes' is omitted since this model requires input of fixed size
    warmup: 30
    repeat: 10
    reduction: "median"
  backend: "default"
  target: "cpu"

Model:
  name: "SFace"
  modelPath: "models/face_recognition_sface/face_recognition_sface_2021dec.onnx"