Benchmark:
  name: "Face Recognition Benchmark"
  type: "Recognition"
  data:
    path: "data/face_recognition"
    files: ["Aaron_Tippin_0001.jpg", "Alvaro_Uribe_0028.jpg", "Alvaro_Uribe_0029.jpg", "Jose_Luis_Rodriguez_Zapatero_0001.jpg"]
  metric: # 'sizes' is omitted since this model requires input of fixed size
    warmup: 30
    repeat: 10
  backend: "default"
  target: "cpu"

Model:
  name: "SFace"
