Benchmark:
  name: "Facial Expression Recognition Benchmark"
  type: "Recognition"
  data:
    path: "data/facial_expression_recognition/fer_evaluation"
    files: ["RAF_test_0_61.jpg", "RAF_test_0_30.jpg", "RAF_test_6_25.jpg"]
  metric: # 'sizes' is omitted since this model requires input of fixed size
    warmup: 30
    repeat: 10
  backend: "default"
  target: "cpu"

Model:
  name: "FacialExpressionRecog"
