Benchmark:
  name: "License Plate Detection Benchmark"
  type: "Detection"
  data:
    path: "data/license_plate_detection"
    files: ["1.jpg", "2.jpg", "3.jpg", "4.jpg"]
    sizes: # [[w1, h1], ...], Omit to run at original scale
      - [320, 240]
  metric:
    warmup: 30
    repeat: 10
  backend: "default"
  target: "cpu"

Model:
  name: "LPD_YuNet"
  confThreshold: 0.8
  nmsThreshold: 0.3
  topK: 5000
  keepTopK: 750
