Benchmark:
  name: "Object Tracking Benchmark"
  type: "Tracking"
  data:
    type: "TrackingVideoLoader"
    path: "data/object_tracking"
    files: ["throw_cup.mp4"]
  metric:
    type: "Tracking"
    reduction: "gmean"
  backend: "default"
  target: "cpu"

Model:
  name: "DaSiamRPN"
