Benchmark:
  name: "Object Detection Benchmark"
  type: "Detection"
  data:
    path: "data/object_detection"
    files: ["1.png", "2.png", "3.png"]
    sizes:
      - [416, 416]
  metric:
    warmup: 30
    repeat: 10
  backend: "default"
  target: "cpu"

Model:
  name: "NanoDet"
  prob_threshold: 0.35
  iou_threshold: 0.6
