Benchmark:
  name: "Object Detection Benchmark"
  type: "Detection"
  data:
    path: "data/object_detection"
    files: ["1.png", "2.png", "3.png"]
    sizes:
      - [640, 640]
  metric:
    warmup: 30
    repeat: 10
  backend: "default"
  target: "cpu"

Model:
  name: "YoloX"
  confThreshold: 0.35
  nmsThreshold: 0.5
  objThreshold: 0.5
