Benchmark:
  name: "Object Detection Benchmark"
  type: "Detection"
  data:
    path: "benchmark/data/object_detection"
    files: ["1.png", "2.png", "3.png"]
    sizes:
      - [640, 640]
  metric:
    warmup: 30
    repeat: 10
    reduction: "median"
  backend: "default"
  target: "cpu"

Model:
  name: "YoloX"
  modelPath: "models/object_detection_yolox/object_detection_yolox_2022nov.onnx"
  confThreshold: 0.35
  nmsThreshold: 0.5
  objThreshold: 0.5

