Benchmark:
  name: "Palm Detection Benchmark"
  type: "Detection"
  data:
    path: "data/palm_detection_20230125"
    files: ["palm1.jpg", "palm2.jpg", "palm3.jpg"]
    sizes: # [[w1, h1], ...], Omit to run at original scale
      - [192, 192]
  metric:
    warmup: 30
    repeat: 10
  backend: "default"
  target: "cpu"

Model:
  name: "MPPalmDet"
  scoreThreshold: 0.5
  nmsThreshold: 0.3
  topK: 1
