Benchmark:
  name: "QRCode Detection and Decoding Benchmark"
  type: "Detection"
  data:
    path: "benchmark/data/qrcode"
    files: ["opencv.png", "opencv_zoo.png"]
    sizes:
      - [100, 100]
      - [300, 300]
  metric:
    warmup: 30
    repeat: 10
    reduction: "median"
  backend: "default"
  target: "cpu"

Model:
  name: "WeChatQRCode"
  detect_prototxt_path: "models/qrcode_wechatqrcode/detect_2021nov.prototxt"
  detect_model_path: "models/qrcode_wechatqrcode/detect_2021nov.caffemodel"
  sr_prototxt_path: "models/qrcode_wechatqrcode/sr_2021nov.prototxt"
  sr_model_path: "models/qrcode_wechatqrcode/sr_2021nov.caffemodel"