Benchmark:
  name: "QRCode Detection and Decoding Benchmark"
  type: "Detection"
  data:
    path: "data/qrcode"
    files: ["opencv.png", "opencv_zoo.png"]
    sizes:
      - [100, 100]
      - [300, 300]
  metric:
    warmup: 30
    repeat: 10
    reduction: "median"
  backend: "default"
  target: "cpu"

Model:
  name: "WeChatQRCode"
