Benchmark:
  name: "Text Recognition Benchmark"
  type: "Recognition"
  data:
    path: "data/text"
    files: ["1.jpg", "2.jpg", "3.jpg"]
  metric: # 'sizes' is omitted since this model requires input of fixed size
    warmup: 30
    repeat: 10
  backend: "default"
  target: "cpu"

Model:
  name: "CRNN"
