Benchmark:
  name: "Text Detection Benchmark"
  data:
    path: "benchmark/data/text"
    files: ["1.jpg", "2.jpg", "3.jpg"]
  metric:
    sizes: # [[w1, h1], ...], Omit to run at original scale
      - [640, 480]
    warmup: 3
    repeat: 10
    batchSize: 1
    reduction: 'median'
  backend: "default"
  target: "cpu"

Model:
  name: "DB"
  modelPath: "models/text_detection_db/text_detection_DB_TD500_resnet18_2021sep.onnx"
  binaryThreshold: 0.3
  polygonThreshold: 0.5
  maxCandidates: 200
  unclipRatio: 2.0