Benchmark:
  name: "Text Recognition Benchmark"
  data:
    path: "benchmark/data/text"
    files: ["1.jpg", "2.jpg", "3.jpg"]
    useLabel: True
  metric: # 'sizes' is omitted since this model requires input of fixed size
    warmup: 3
    repeat: 10
    batchSize: 1
    reduction: 'median'
  backend: "default"
  target: "cpu"

Model:
  name: "CRNN"
  modelPath: "models/text_recognition_crnn/text_recognition_CRNN_VGG_BiLSTM_CTC_2021sep.onnx"